<Project>
  <PropertyGroup>
    <Company>RuneUO</Company>
    <Authors>andreakarasho and ClassicUO contributors, RuneUO contributors</Authors>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <FileVersion>1.1.0.0</FileVersion>
    <Copyright>Copyright (c) andreakarasho and ClassicUO contributors, RuneUO contributors</Copyright>
    <PackageProjectUrl>https://github.com/RuneUO/runeuo-client</PackageProjectUrl>
    <Description>RuneUO, an Ultima Online client based on ClassicUO.</Description>
  </PropertyGroup>
</Project>