name: Deploy

on:
  workflow_dispatch: {}
  workflow_run:
    branches: [main, beta]
    workflows: [Build-Test]
    types:
      - completed

env:
  RUNEUO_VERSION: "1.1.0.${{ github.run_number }}"
  OUTPUT_PATH: "dist"
  CLIENT_PROJECT_PATH: "src/RuneUO.Client/RuneUO.Client.csproj"
  BOOT_PROJECT_PATH: "src/RuneUO.Bootstrap/src/RuneUO.Bootstrap.csproj"

  BRANCH_NAME: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch || github.ref_name }}
  COMMIT_SHA: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.sha }}
  RELEASE_TAG: RuneUO-${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch || github.ref_name }}-release

  DOTNET_NOLOGO: false
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: skip

jobs:
  tag:
    if: >-
      github.repository == 'RuneUO/runeuo-client' &&
      (github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ env.COMMIT_SHA }}

      - name: Move tag to latest commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -f "${{ env.RELEASE_TAG }}" "${{ env.COMMIT_SHA }}"
          git push -f origin "${{ env.RELEASE_TAG }}"

  build:
    needs: tag
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    env:
      ZIP_NAME: "RuneUO-${{ matrix.target }}-release.zip"
      MANIFEST_NAME: "RuneUO-${{ matrix.target }}-manifest.xml"
      DEV_BUILD: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch != 'main' || github.event_name == 'workflow_dispatch' && github.ref_name != 'main' }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            target: win-x64
          - os: ubuntu-22.04
            target: linux-x64
          - os: macos-14
            target: osx-x64

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ env.COMMIT_SHA }}

      - name: Get submodules
        run: git config --global url."https://".insteadOf git:// && git submodule update --init --recursive

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Build Bootstrap app
        run: dotnet publish "${{ env.BOOT_PROJECT_PATH }}" -c Release -o "${{ env.OUTPUT_PATH }}" /p:AssemblyVersion=${{ env.RUNEUO_VERSION }} /p:FileVersion=${{ env.RUNEUO_VERSION }} /p:OutputType=WinExe

      - name: Build RuneUO
        run: dotnet publish "${{ env.CLIENT_PROJECT_PATH }}" -c Release -r "${{ matrix.target }}" -o "${{ env.OUTPUT_PATH }}" /p:IS_DEV_BUILD=${{ env.DEV_BUILD }} /p:AssemblyVersion=${{ env.RUNEUO_VERSION }} /p:FileVersion=${{ env.RUNEUO_VERSION }} /p:NativeLib=Shared /p:OutputType=Library

      - name: Create manifest
        run: |
          dotnet run --project tools/ManifestCreator/ManifestCreator.csproj "${{ env.OUTPUT_PATH }}" "${{ env.RUNEUO_VERSION }}" "${{ env.ZIP_NAME }}"
          mkdir upload
          mv manifest.xml "upload/${{ env.MANIFEST_NAME }}"

      - name: Create package
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: "zip"
          directory: ${{ env.OUTPUT_PATH }}
          filename: ${{ env.ZIP_NAME }}

      - name: Move output
        run: mv "${{ env.OUTPUT_PATH }}/${{ env.ZIP_NAME }}" upload

      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "upload/${{ env.ZIP_NAME }},upload/${{ env.MANIFEST_NAME }}"
          name: "RuneUO ${{ env.BRANCH_NAME }} release"
          body: "Unsigned build: use it at your own risk."
          draft: false
          prerelease: ${{ env.BRANCH_NAME != 'main' }}
          allowUpdates: true
          replacesArtifacts: true
          tag: "${{ env.RELEASE_TAG }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ env.COMMIT_SHA }}
